-- RAW admin — database setup.
-- Run once: Supabase → SQL Editor → New query → paste this whole file → Run.
-- Safe to run again (it only creates what's missing).

-- Prices, products, styles, settings… (one row per section, edited from /admin)
create table if not exists public.config (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id         bigint generated by default as identity (start with 1001) primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status     text not null default 'new' check (status in ('new','confirmed','shipped','delivered','returned','cancelled')),
  source     text not null default 'website',
  name       text not null,
  phone      text not null,
  wilaya     text not null,
  commune    text not null default '',
  address    text not null default '',
  delivery   text not null default 'home' check (delivery in ('home','desk')),
  note       text not null default '',
  items      jsonb not null default '[]',
  subtotal   integer not null default 0,
  shipping   integer not null default 0,
  discount   integer not null default 0,
  coupon     text not null default '',
  total      integer not null default 0,
  attempts   integer not null default 0,
  tracking   text not null default '',
  admin_note text not null default '',
  flag       text not null default '',
  history    jsonb not null default '[]'
);
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_phone_idx on public.orders (phone);

create table if not exists public.bookings (
  id         bigint generated by default as identity (start with 101) primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status     text not null default 'new' check (status in ('new','confirmed','done','cancelled','noshow')),
  source     text not null default 'website',
  style      text not null default '',
  style_name text not null default '',
  picks      jsonb not null default '{}',
  estimate   integer not null default 0,
  "date"     date,
  "time"     text not null default '',
  area       text not null default '',
  name       text not null default '',
  phone      text not null default '',
  instagram  text not null default '',
  price      integer,
  deposit    integer not null default 0,
  note       text not null default '',
  admin_note text not null default '',
  history    jsonb not null default '[]'
);
create index if not exists bookings_created_idx on public.bookings (created_at desc);
create index if not exists bookings_status_idx on public.bookings (status);

create table if not exists public.coupons (
  code       text primary key,
  type       text not null check (type in ('percent','fixed')),
  value      integer not null check (value > 0),
  active     boolean not null default true,
  min_order  integer not null default 0,
  max_uses   integer,
  uses       integer not null default 0,
  expires    date,
  created_at timestamptz not null default now()
);
insert into public.coupons (code, type, value) values ('RAW10', 'percent', 10), ('ROYAL', 'fixed', 300)
on conflict (code) do nothing;

-- Rate limiting for the login, order and booking forms.
create table if not exists public.throttle (
  key      text primary key,
  hits     integer not null,
  reset_at timestamptz not null
);

create or replace function public.throttle_hit(p_key text, p_limit integer, p_window integer)
returns boolean language plpgsql security definer set search_path = public as $$
declare h integer;
begin
  delete from throttle where reset_at < now() - interval '1 day';
  insert into throttle as t (key, hits, reset_at) values (p_key, 1, now() + make_interval(secs => p_window))
  on conflict (key) do update set
    hits     = case when t.reset_at < now() then 1 else t.hits + 1 end,
    reset_at = case when t.reset_at < now() then now() + make_interval(secs => p_window) else t.reset_at end
  returning hits into h;
  return h <= p_limit;
end $$;

create or replace function public.coupon_redeem(p_code text)
returns void language sql security definer set search_path = public as $$
  update coupons set uses = uses + 1 where code = p_code;
$$;

-- Lock everything down: only the website's server (service-role key) can read or write.
-- No policies on purpose — the public "anon" key gets nothing.
alter table public.config   enable row level security;
alter table public.orders   enable row level security;
alter table public.bookings enable row level security;
alter table public.coupons  enable row level security;
alter table public.throttle enable row level security;
revoke execute on function public.throttle_hit(text, integer, integer) from public, anon, authenticated;
revoke execute on function public.coupon_redeem(text) from public, anon, authenticated;
grant execute on function public.throttle_hit(text, integer, integer) to service_role;
grant execute on function public.coupon_redeem(text) to service_role;

-- Product photos uploaded from the admin (public so the shop can show them; only the server can upload).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('media', 'media', true, 5242880, array['image/webp','image/jpeg','image/png','image/avif','image/gif'])
on conflict (id) do nothing;
